export default {
    FETCH_CHARACTER_SEARCH_SUCCESS: 'FETCH_CHARACTER_SEARCH_SUCCESS',
    FETCH_CHARACTER_SEARCH_ERROR: 'FETCH_CHARACTER_SEARCH_ERROR',
    FETCH_CHARACTER_SEARCH_REQUEST: 'FETCH_CHARACTER_SEARCH_REQUEST'
}